feat: new update for exercise 4 using different inputs

diff --git a/.github/workflows/ejercicio4.yaml b/.github/workflows/ejercicio4.yaml
--- a/.github/workflows/ejercicio4.yaml
+++ b/.github/workflows/ejercicio4.yaml
@@ -14,20 +14,28 @@ jobs:
   calcular:
     runs-on: ubuntu-latest
     steps:
-      - name: Ingresar operación y operandos en el orden OPERACION N1 N2
+      - name: Ingresar operación y operandos
         id: inputs
         run: |
-          echo "operacion=${{ github.event.inputs.operacion }}" >> $GITHUB_ENV
-          echo "operando1=${{ github.event.inputs.operando1 }}" >> $GITHUB_ENV
-          echo "operando2=${{ github.event.inputs.operando2 }}" >> $GITHUB_ENV
+          read -p "Operación (+,-,*,/): " operacion
+          read -p "Primer operando: " operando1
+          read -p "Segundo operando: " operando2
+          echo "::set-output name=operacion::$operacion"
+          echo "::set-output name=operando1::$operando1"
+          echo "::set-output name=operando2::$operando2"
 
       - name: Ejecutar calculadora
         run: |
-          operacion=${{ env.operacion }}
-          operando1=${{ env.operando1 }}
-          operando2=${{ env.operando2 }}
+          operacion=${{ steps.inputs.outputs.operacion }}
+          operando1=${{ steps.inputs.outputs.operando1 }}
+          operando2=${{ steps.inputs.outputs.operando2 }}
 
           # Validación de los operandos
+          if ! [[ "$operacion" =~ ^[+*/-]$ ]]; then
+            echo "Error: Operación no válida."
+            exit 1
+          fi
+
           if ! [[ "$operando1" =~ ^[0-9]+$ ]]; then
             echo "Error: El primer operando no es un número válido."
             exit 1
@@ -40,21 +48,17 @@ jobs:
 
           # Realizar la operación
           case $operacion in
-            "sumar")
+            "+")
               resultado=$(echo "$operando1 + $operando2" | bc)
               ;;
-            "restar")
+            "-")
               resultado=$(echo "$operando1 - $operando2" | bc)
               ;;
-            "multiplicar")
+            "*")
               resultado=$(echo "$operando1 * $operando2" | bc)
               ;;
-            "dividir")
+            "/")
               resultado=$(echo "scale=2; $operando1 / $operando2" | bc)
-              ;;
-            *)
-              echo "Error: Operación no válida."
-              exit 1
               ;;
           esac
 
